### PR TITLE
Plot labs

### PR DESCRIPTION
**Pull request by PhilBoileau**
Replacing "empirical risk" by "cross-validated risk" or "CV risk" in plot labels, column names, and documentation.

### CODE REVIEW

**Review by bcollica — COMMENTED** [review]
Hey Phil, everything looks normal to me.  I went ahead and changed "Risk" to "CV Risk" in the legend for the eigenvalue plots, but that's it.  Were you experiencing specific errors when you tried to change things before?

**Comment by PhilBoileau** [comment]
Great, thanks for reviewing and updating the eigenvalue plot legend. The only (minor) remaining issue was that the column names in the 5-number summary tables of the cross-validated risk distributions are in lower case, and one or two have underscores instead of spaces. I'd prefer names that a more "publication ready". I tried changing this directly in `empRiskByClass()`, but it caused issues downstream. Any suggestions?

**Comment by bcollica** [comment]
Ah, okay.  Let me take a closer look this afternoon, I’m sure it’s a quick fix!

Brian

**Comment by PhilBoileau** [comment]
Sounds good, thanks. There's no rush!

**Comment by bcollica** [comment]
Hey Phil, I think the labels should be good to go now.  Also, if you like,
I can change empRiskByClass to be cvRiskByClass.  It's minor, but it would
be more consistent.  Or maybe it's best to hold off until another version
update, seeing as how we just got listed on CRAN?  Whatever you think makes
sense.

Brian

**Comment by PhilBoileau** [comment]
Awesome, thank you for the quick fix.
That's a good point. If you have the bandwidth, I think we should make the change sooner rather than later.

**Comment by bcollica** [comment]
All set, empRiskByClass is now cvRiskByClass.  I ran a few tests and all
seemed well, but let me know if there are any issues.  Changing the column
names in the other summary tables will take a bit more care since they are
explicitly referenced in other functions, but I can handle that when I add
the new matrix stats like condition number.  That might also be a good time
to solidify a consistent naming convention for future additions.

Brian

**Comment by PhilBoileau** [comment]
Perfect, thanks. I'll take a look around, and if all looks well, I'll merge this PR. That sounds like a good plan -- let's plan to discuss this during our next meeting.

**Pull request merged**
